### PR TITLE
 Make Map.Initialize() virtual and add GetCellsInRectangle() 

### PR DESCRIPTION
**Pull request by aodendaal**
Initialize() should be virtual so that a custom map can override the default behaviour to initialize its own internal state.

Sorry I didn't add GetBorderCellsInRectangle() but I'm on a deadline for 7DRL Challenge 2019

### CODE REVIEW

**Comment by FaronBracy** [comment]
Thanks again. Would like to see your 7DRL. I'm also curious about how well RogueSharp worked for you.

**Comment by aodendaal** [comment]
You can play my 7DRL online http://fengol.itch.io/ring-of-erdna

I found the library conveniently easy to use and simple to extend with the small changes I posted. It's definitely my "goto" for a tile management library.

I also learnt a lot from your V3 tutorial!

**Comment by FaronBracy** [comment]
> You can play my 7DRL online http://fengol.itch.io/ring-of-erdna

This is really cool. I've been wanting to learn more about Unity. Thanks for sharing this.

By the way, I got stuck on the first floor after killing all the monsters. Not sure if stairs are implemented yet or if they were in some disconnected part of the dungeon that I couldn't find my way into.

**Comment by aodendaal** [comment]
Sorry for the delay responding. I was finishing my project and I'm busy judging. I also got the error with a sealed up room. Must be a bug in my generation code. Please re-fresh the page and try again.

**Pull request merged**
